# Generated by Django 5.0 on 2026-03-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_aisle_category_product_default_store'),
        ('stores', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaisle',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_aisles', to='products.productcategory'),
        ),
    ]
