# Generated by Django 5.0 on 2026-03-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_aisle_category_product_default_store'),
        ('stores', '0003_aisle_category_product_default_store'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storeaisle',
            constraint=models.UniqueConstraint(condition=models.Q(('product_category__isnull', False)), fields=('store', 'product_category'), name='unique_store_product_category'),
        ),
    ]
