# Generated by Django 5.0 on 2026-03-19 09:20

from django.db import migrations, models

NON_FOOD_CATEGORIES = ['Pulizia casa', 'Igiene personale', 'Farmaci']


def set_is_food(apps, schema_editor):
    ProductCategory = apps.get_model('products', 'ProductCategory')
    ProductCategory.objects.filter(name__in=NON_FOOD_CATEGORIES).update(is_food=False)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_food',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_is_food, migrations.RunPython.noop),
    ]
