# Generated by Django 5.0 on 2026-03-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_fix_icon_add_sanitaria'),
        ('stores', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_products', to='stores.store'),
        ),
    ]
