# Generated by Django 5.0 on 2026-03-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppingitem_source_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinghistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
